const icons = {
  //FA
  'ellipsis-h': require('./ellipsis-h').default,
  'plus': require('./plus').default,
  'check': require('./check').default,
  'share': require('./share').default,
  'copy': require('./copy').default,
  'cog': require('./cog').default,
  'globe': require('./globe').default,
  'search': require('./search').default,
  'heart': require('./heart').default,
  'moon-stars': require('./moon-stars').default,
  'sun': require('./sun').default,
  'bars': require('./bars').default,
  'home': require('./home').default,
  'chart': require('./chart').default,
  'bell': require('./bell').default,
  'chevron-down': require('./chevron-down').default,
  'dot-circle': require('./dot-circle').default,
  'chevron-left': require('./chevron-left').default,
  'chevron-right': require('./chevron-right').default,
  'times': require('./times').default,
  'star': require('./star').default,
  'comments': require('./comments').default,
  'power-off': require('./power-off').default,
  'keyboard': require('./keyboard').default,
  'mouse': require('./mouse').default,
  'desktop': require('./desktop').default,
  'comment-alt-music': require('./comment-alt-music').default,
  'clock': require('./clock').default,
  'angle-down': require('./angle-down').default,
  'angle-right': require('./angle-right').default,
  'caret-down': require('./caret-down').default,
  'table': require('./table').default,
  'icons': require('./icons').default,
  'scroll': require('./scroll').default,
  'browser': require('./browser').default,
};

export default icons;
